// [Header file created by Help ID Fixer at 08:57:23 on 07 Jan 2005]
// [Allocated ID range = 2000 to 3999]

#define IDH_CURSOR_LOCATION                                                              2000
#define IDH_CUSTOMISESOURCE_ABANDON_VIEW                                                 2001
#define IDH_CUSTOMISESOURCE_PRINT_NO_DIALOG                                              2002
#define IDH_CUSTOMISESOURCE_UNIQUE_TASK_ID_NUMBERING                                     2003
#define IDH_CUSTOMIZE_DIALOG                                                             2004
#define IDH_EDIT_REDO_DROPDOWN                                                           2005
#define IDH_EDIT_UNDO_DROPDOWN                                                           2006
#define IDH_ENDBY_SOFT                                                                   2007
#define IDH_FORMAT_BACKGROUND_COLOUR_DROPDOWN                                            2008
#define IDH_FORMAT_COLOUR_DROPDOWN                                                       2009
#define IDH_FORMAT_FONT                                                                  2010
#define IDH_FORMAT_FONT_SIZE                                                             2011
#define IDH_INTERACTIVE_PROGRESS                                                         2012
#define IDH_LOCKOUT_SETTINGS                                                             2013
#define IDH_MAINFRAME_DELETE_PROJECT                                                     2014
#define IDH_MAINFRAME_FILE_NEW                                                           2015
#define IDH_NO_ASSOCIATED_MENU_HELP                                                      2016
#define IDH_RISKANALYSIS                                                                 2017
#define IDH_SELECT_CONSTRAINT                                                            2018
#define IDH_TEAMPLAN_TUTORIAL                                                            2019
#define IDH_TIME_UNIT                                                                    2020
#define IDH_TITAN_TYPE_ALL_TABULAR_REPORTS                                               2021
#define IDH_TITAN_TYPE_APP_EXIT                                                          2022
#define IDH_TITAN_TYPE_ASSIGN_RESOURCE                                                   2023
#define IDH_TITAN_TYPE_BARCHART_DEFAULTS                                                 2024
#define IDH_TITAN_TYPE_BASELINE_MANAGER                                                  2025
#define IDH_TITAN_TYPE_BATCH_ADD_TASK                                                    2026
#define IDH_TITAN_TYPE_BOOKIN_BOOKED_TO_PROJECT                                          2027
#define IDH_TITAN_TYPE_BOOKOUT_TAGGED_OBJECTS                                            2028
#define IDH_TITAN_TYPE_CHAT                                                              2029
#define IDH_TITAN_TYPE_CLOSE_PROJECT                                                     2030
#define IDH_TITAN_TYPE_COPY                                                              2031
#define IDH_TITAN_TYPE_COPY_ALLOCATIONS_TO_GROUP                                         2032
#define IDH_TITAN_TYPE_COPY_PROPERTIES_TO_DEFAULT                                        2033
#define IDH_TITAN_TYPE_CUT                                                               2034
#define IDH_TITAN_TYPE_DEFAULT_BARCHART_VIEW                                             2035
#define IDH_TITAN_TYPE_DEFAULT_TABLE                                                     2036
#define IDH_TITAN_TYPE_DELETECONSTRAINT                                                  2037
#define IDH_TITAN_TYPE_DELETE_AND_RELINK                                                 2038
#define IDH_TITAN_TYPE_DELETE_PROJECT                                                    2039
#define IDH_TITAN_TYPE_EDIT_DELETE                                                       2040
#define IDH_TITAN_TYPE_EDIT_FILTER                                                       2041
#define IDH_TITAN_TYPE_EDIT_PROPERTIES                                                   2042
#define IDH_TITAN_TYPE_EDIT_REDO                                                         2043
#define IDH_TITAN_TYPE_EDIT_SORT                                                         2044
#define IDH_TITAN_TYPE_EDIT_TABLE                                                        2045
#define IDH_TITAN_TYPE_EDIT_UNDO                                                         2046
#define IDH_TITAN_TYPE_EDIT_VIEW                                                         2047
#define IDH_TITAN_TYPE_ENDBY                                                             2048
#define IDH_TITAN_TYPE_ENDON                                                             2049
#define IDH_TITAN_TYPE_ENTER_PROGRESS_TASK                                               2050
#define IDH_TITAN_TYPE_FAKE_INSERT_ANNOTATION_TOKEN                                      2051
#define IDH_TITAN_TYPE_FILE_NEW                                                          2052
#define IDH_TITAN_TYPE_FILE_OPEN                                                         2053
#define IDH_TITAN_TYPE_FILE_SAVE                                                         2054
#define IDH_TITAN_TYPE_FILE_SAVE_AS                                                      2055
#define IDH_TITAN_TYPE_FIND                                                              2056
#define IDH_TITAN_TYPE_FORCED_UNBOOK_FROM_PROJECT                                        2057
#define IDH_TITAN_TYPE_FORMATMENU_FONT                                                   2058
#define IDH_TITAN_TYPE_FORMAT_BARCHART                                                   2059
#define IDH_TITAN_TYPE_FORMAT_CELLS                                                      2060
#define IDH_TITAN_TYPE_FORMAT_DATEZONE                                                   2061
#define IDH_TITAN_TYPE_FORMAT_DEFAULT_TABLE_FONTS                                        2062
#define IDH_TITAN_TYPE_FORMAT_GRIDS                                                      2063
#define IDH_TITAN_TYPE_FORMAT_RULING_LINES                                               2064
#define IDH_TITAN_TYPE_HELP_ABOUT                                                        2065
#define IDH_TITAN_TYPE_HELP_ASTA_ON_THE_WEB                                              2066
#define IDH_TITAN_TYPE_HELP_CUSTOMER_SERVICES                                            2067
#define IDH_TITAN_TYPE_HELP_FAQ_ON_THE_WEB                                               2068
#define IDH_TITAN_TYPE_HELP_LICENCE                                                      2069
#define IDH_TITAN_TYPE_HELP_LICENCE_STATUS                                               2070
#define IDH_TITAN_TYPE_HELP_MOVE_LICENCE                                                 2071
#define IDH_TITAN_TYPE_HELP_OBTAIN_LOAN_LICENCE                                          2072
#define IDH_TITAN_TYPE_HELP_WHATS_THIS                                                   2073
#define IDH_TITAN_TYPE_HIERARCHY_HAMMOCK_MEMBERS                                         2074
#define IDH_TITAN_TYPE_HIERARCHY_HIDE_SUBTASKS                                           2075
#define IDH_TITAN_TYPE_HIERARCHY_OPEN_AS_SUMMARY                                         2076
#define IDH_TITAN_TYPE_HIERARCHY_SHOW_ALL_SUBTASKS                                       2077
#define IDH_TITAN_TYPE_HIERARCHY_SHOW_SUBTASKS                                           2078
#define IDH_TITAN_TYPE_INDENT                                                            2079
#define IDH_TITAN_TYPE_INSERT                                                            2080
#define IDH_TITAN_TYPE_INSERT_ANNOTATION_FIELD                                           2081
#define IDH_TITAN_TYPE_INSERT_AT_END_OF_SUMMARY                                          2082
#define IDH_TITAN_TYPE_INSERT_COLUMN                                                     2083
#define IDH_TITAN_TYPE_INSERT_HAMMOCK                                                    2084
#define IDH_TITAN_TYPE_L4FILES                                                           2085
#define IDH_TITAN_TYPE_LIBRARY_EXPLORER                                                  2086
#define IDH_TITAN_TYPE_LINKTASKS                                                         2087
#define IDH_TITAN_TYPE_MACRO_LOAD                                                        2088
#define IDH_TITAN_TYPE_MACRO_SAVE                                                        2089
#define IDH_TITAN_TYPE_MACRO_VB                                                          2090
#define IDH_TITAN_TYPE_MORE_FILTERS                                                      2091
#define IDH_TITAN_TYPE_MORE_PROJECT_VIEWS                                                2092
#define IDH_TITAN_TYPE_MORE_SORTS                                                        2093
#define IDH_TITAN_TYPE_MORE_TABLES                                                       2094
#define IDH_TITAN_TYPE_MORE_TABULAR_REPORTS                                              2095
#define IDH_TITAN_TYPE_MORE_USER_VIEWS                                                   2096
#define IDH_TITAN_TYPE_MOVE_BARS_INTO_CHART                                              2097
#define IDH_TITAN_TYPE_NATURAL_ORDER                                                     2098
#define IDH_TITAN_TYPE_NEW_FILTER                                                        2099
#define IDH_TITAN_TYPE_NEW_SORT                                                          2100
#define IDH_TITAN_TYPE_NEW_TABLE                                                         2101
#define IDH_TITAN_TYPE_NEW_TABULAR_REPORT                                                2102
#define IDH_TITAN_TYPE_NEW_VIEW                                                          2103
#define IDH_TITAN_TYPE_NO_FILTER                                                         2104
#define IDH_TITAN_TYPE_NO_TOOLBAR                                                        2105
#define IDH_TITAN_TYPE_OLE_ANNOTATION                                                    2106
#define IDH_TITAN_TYPE_OPTIONS                                                           2107
#define IDH_TITAN_TYPE_OUTDENT                                                           2108
#define IDH_TITAN_TYPE_PAGE_BREAK                                                        2109
#define IDH_TITAN_TYPE_PASTE                                                             2110
#define IDH_TITAN_TYPE_PICTURE_ANNOTATION                                                2111
#define IDH_TITAN_TYPE_PP_HELP                                                           2112
#define IDH_TITAN_TYPE_PRED_SUCC                                                         2113
#define IDH_TITAN_TYPE_PRINT                                                             2114
#define IDH_TITAN_TYPE_PRINT_PREVIEW                                                     2115
#define IDH_TITAN_TYPE_PROGRESS_TASK_FROM_ALLOCATION                                     2116
#define IDH_TITAN_TYPE_PROJECT_PROPERTIES                                                2117
#define IDH_TITAN_TYPE_RESCHEDULE                                                        2118
#define IDH_TITAN_TYPE_RESOURCE_LEVEL                                                    2119
#define IDH_TITAN_TYPE_SAVE_FILTER_AS                                                    2120
#define IDH_TITAN_TYPE_SAVE_SORT_AS                                                      2121
#define IDH_TITAN_TYPE_SAVE_TABLE_AS                                                     2122
#define IDH_TITAN_TYPE_SAVE_VIEW_AS                                                      2123
#define IDH_TITAN_TYPE_SELECT_ALL                                                        2124
#define IDH_TITAN_TYPE_SELECT_BY_FILTER                                                  2125
#define IDH_TITAN_TYPE_SELECT_LINKS                                                      2126
#define IDH_TITAN_TYPE_SERVER_PASSWORD                                                   2127
#define IDH_TITAN_TYPE_SET_LOCATOR                                                       2128
#define IDH_TITAN_TYPE_SORT_BY_SS_COLUMN                                                 2129
#define IDH_TITAN_TYPE_STARTAFTER                                                        2130
#define IDH_TITAN_TYPE_STARTON                                                           2131
#define IDH_TITAN_TYPE_SUMMARISE_BAR                                                     2132
#define IDH_TITAN_TYPE_TAG_BRANCH_READ_ONLY                                              2133
#define IDH_TITAN_TYPE_TAG_BRANCH_READ_WRITE                                             2134
#define IDH_TITAN_TYPE_TAG_BRANCH_READ_WRITE_DELETE                                      2135
#define IDH_TITAN_TYPE_TAG_NOT_BOOKED_OUT                                                2136
#define IDH_TITAN_TYPE_TAG_NOT_BOOKED_OUT_BRANCH                                         2137
#define IDH_TITAN_TYPE_TAG_READ_ONLY                                                     2138
#define IDH_TITAN_TYPE_TAG_READ_WRITE                                                    2139
#define IDH_TITAN_TYPE_TAG_READ_WRITE_DELETE                                             2140
#define IDH_TITAN_TYPE_TASK_WBN                                                          2141
#define IDH_TITAN_TYPE_TEXT_ANNOTATION                                                   2142
#define IDH_TITAN_TYPE_TOOLS_CUSTOMIZE                                                   2143
#define IDH_TITAN_TYPE_TOOLS_MACROS                                                      2144
#define IDH_TITAN_TYPE_TOOLS_SPELLCHECK                                                  2145
#define IDH_TITAN_TYPE_TOOLS_UDF_MANAGER                                                 2146
#define IDH_TITAN_TYPE_UNDO_ALL                                                          2147
#define IDH_TITAN_TYPE_UNIQUE_TASK_ID_NUMBERING                                          2148
#define IDH_TITAN_TYPE_UNLINKTASKS                                                       2149
#define IDH_TITAN_TYPE_UP_ONE_LEVEL                                                      2150
#define IDH_TITAN_TYPE_VIEWCLOSEHISTO                                                    2151
#define IDH_TITAN_TYPE_VIEWNEWHISTO                                                      2152
#define IDH_TITAN_TYPE_VIEW_HISTOGRAM_VIEW                                               2153
#define IDH_TITAN_TYPE_VIEW_PROJECT_TREE                                                 2154
#define IDH_TITAN_TYPE_VIEW_REFRESH                                                      2155
#define IDH_TITAN_TYPE_VIEW_ZOOM                                                         2156
#define IDH_TITAN_TYPE_WINDOW_ARRANGE                                                    2157
#define IDH_TITAN_TYPE_WINDOW_CASCADE                                                    2158
#define IDH_TITAN_TYPE_WINDOW_NEW_WINDOW                                                 2159
#define IDH_TITAN_TYPE_WINDOW_TILE_HORZ                                                  2160
#define IDH_TITAN_TYPE_WINDOW_TILE_VERT                                                  2161
#define IDH_TITAN_TYPE_WORKBETWEEN                                                       2162
#define IDH_VIEW_SELECTOR                                                                2163
#define IDH_ZOOM                                                                         2164
#define IDH_PUBLISH_OPTIONS                                                              2165
#define IDH_IMPORT_RESOURCES_MENU                                                        2166
#define IDH_PUBLISH                                                                      2167
#define IDH_TITAN_TYPE_RESCHEDULE_FWD_PASS_ONLY                                          2168
#define IDH_LINK_FROM_TASK                                                               2169
#define IDH_TITAN_TYPE_PASTE_VALUES                                                      2170
#define IDH_USER_LEVEL_MENU                                                              2171
#define IDH_RESOURCE_SEARCH                                                              2172
#define IDH_VIEW_CLOSE                                                                   2173
#define IDH_TITAN_TYPE_HELP_ASTA_WEB3                                                    2174
#define IDH_SHOW_ALL_LEVELS                                                              2175
#define IDH_SHOW_1_LEVEL                                                                 2176
#define IDH_SHOW_2_LEVELS                                                                2177
#define IDH_SHOW_3_LEVELS                                                                2178
#define IDH_SHOW_4_LEVELS                                                                2179
#define IDH_SHOW_5_LEVELS                                                                2180
#define IDH_SHOW_6_LEVELS                                                                2181
#define IDH_SHOW_7_LEVELS                                                                2182
#define IDH_SHOW_8_LEVELS                                                                2183
#define IDH_SHOW_9_LEVELS                                                                2184
#define IDH_TITAN_TYPE_HELP_CHECK_FOR_UPDATE                                             2185
#define IDH_TITAN_TYPE_JAGGED_PROGRESS                                                   2186
#define IDH_FORMAT_HIDE_MARKED_ITEMS                                                     2187
#define IDH_TITAN_TYPE_PTV_CHANGE_FONT                                                   2188
#define IDH_TITAN_TYPE_MORE_VIEWS                                                        2189
#define IDH_TITAN_TYPE_SELECT_VIEW                                                       2190
#define IDH_NEW_PROJECT_WIZARD                                                           2191
#define IDH_NEW_TASKS_WIZARD                                                             2192
#define IDH_CREATE_LINKS_WIZARD                                                          2193
#define IDH_ORGANISE_TASKS_WIZARD                                                        2194
#define IDH_ORGANISE_SPREADSHEET_COLUMNS_WIZARD                                          2195
#define IDH_ENTER_PROGRESS_WIZARD                                                        2196
#define IDH_NEW_CALENDAR_WIZARD                                                          2197

#define IDH_TITAN_TYPE_DISPLAY_SWITCH_FREE_FLOAT                                         2198
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_TOTAL_FLOAT                                        2199
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_CRITICAL_PATH                                      2200
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_PROGRESS_LINE                                      2201
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_PROGRESS_SHADING                                   2202
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_NON_DRIVING_LINKS                                  2203
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_ALL_LINKS                                          2204
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_CONSTRAINTS                                        2205
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_ANNOTATIONS                                        2206
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_BASELINES                                          2207
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_DEMAND_ALLOCATIONS                                 2208
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_SCHEDULED_ALLOCATIONS                              2209
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_COST_ALLOCATIONS                                   2210
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_GRID_LINES                                         2211
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_RULING_LINES                                       2212
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_DATE_ZONE                                          2213
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_NON_WORKING_SHADING                                2214
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_VERTICAL_SHADING                                   2215

#define IDH_TITAN_TYPE_IDM_VIEW_DOCKABLE_PROPERTIES                                      2216
#define IDH_TITAN_TYPE_WBS_MANAGEMENT_DIALOG                                             2217
#define IDH_TITAN_TYPE_SELECT_FILTER                                                     2218
#define IDH_TITAN_TYPE_SELECT_SORT                                                       2219
#define IDH_TITAN_TYPE_SELECT_TABLE                                                      2220
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_STANDARD_WORK_SHADING                              2221 //Ready for v11.0.02
#define IDH_TITAN_TYPE_PATH_TO_TASK_VIEW                                                 2222
#define IDH_TITAN_TYPE_ROLL_UP_TO_ONE_LINE                                               2223
#define IDH_TITAN_TYPE_UNROLL_TASKS                                                      2224

#define IDH_TITAN_TYPE_UNTILE_WINDOWS                                                    2225 // added in 11.0.2
#define IDH_TITAN_TYPE_IDM_HELP_ACTIVATE_RISK_ACTIVATE_SOFTWARE                         2226
#define IDH_TITAN_TYPE_IDM_HELP_ACTIVATE_RISK_REQUEST_TRIAL                             2227
#define IDH_TITAN_TYPE_IDM_HELP_ACTIVATE_RISK_MOVE_LICENCE                              2228

#define IDH_TITAN_TYPE_IDM_SWITCH_TO_RIBBON_MODE                                        2229
#define IDH_TITAN_TYPE_VIEW_LINE_OF_BALANCE_VIEW                                        2230

#define IDH_TITAN_TYPE_VIEWCLOSELOB                                                     2231
#define IDH_TITAN_TYPE_VIEWNEWLOB                                                       2232
#define IDH_TITAN_TYPE_HOLDING_PIN                                                      2233 // BUGFIX 23188 12.0.01 dick broughton 12/10/2011 -- 
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_RBS_EMPTY_RESOURCES                               2234
#define IDH_TITAN_TYPE_DISPLAY_SWITCH_RBS_RESOURCE_SUMMARIES                            2235

#define IDH_TITAN_TYPE_VIEWCLOSEUAT                                                     2236
#define IDH_TITAN_TYPE_VIEWNEWUAT                                                       2237

#define IDH_TITAN_TYPE_RESCHEDULE_BRANCH                                                2238
#define IDH_TITAN_TYPE_RESCHEDULE_VIEW                                                  2239
#define IDH_TITAN_TYPE_RESCHEDULE_SELECTION                                             2240
#define IDH_TITAN_TYPE_RESCHEDULE_PROJECTONCLIENT                                       2241

#define IDH_DYNAMIC_HELP_ITEM                                                          	2250
#define IDH_STATIC_HELP_ITEM                                                            2251

// [Help ID Fixer report: Max ID = 3999]
