// [Header file created by Help ID Fixer at 08:57:23 on 07 Jan 2005]
// [Allocated ID range = 4000 to 4999]

#define IDH_BARCHART_TOOLBAR_INDENT                                                      4000
#define IDH_BARCHART_TOOLBAR_LINK_TASKS                                                  4001
#define IDH_BARCHART_TOOLBAR_MOVE_BARS_INTO_CHART                                        4002
#define IDH_BARCHART_TOOLBAR_OPEN_ASSIGNMENT_VIEW                                        4003
#define IDH_BARCHART_TOOLBAR_OUTDENT                                                     4004
#define IDH_BARCHART_TOOLBAR_PROGRESS_ENTRY_MODE                                         4005
#define IDH_BARCHART_TOOLBAR_RESCHEDULE_BRANCH                                           4006
#define IDH_BARCHART_TOOLBAR_SELECT_CONSTRAINT                                           4007
#define IDH_BARCHART_TOOLBAR_SNAPPING_TIME_UNIT                                          4008
#define IDH_BARCHART_TOOLBAR_SUMMARISE                                                   4009
#define IDH_BARCHART_TOOLBAR_UP_ONE_LEVEL                                                4010
#define IDH_FORMATTING_TOOLBAR_BOLD                                                      4011
#define IDH_FORMATTING_TOOLBAR_FONT                                                      4012
#define IDH_FORMATTING_TOOLBAR_ITALIC                                                    4013
#define IDH_FORMATTING_TOOLBAR_SELECT_COLOUR                                             4014
#define IDH_FORMATTING_TOOLBAR_SIZE                                                      4015
#define IDH_FORMATTING_TOOLBAR_UNDERLINE                                                 4016
#define IDH_HISTO_DELETE                                                                 4017
#define IDH_HISTO_FORMAT                                                                 4018
#define IDH_HISTO_INSERTNEWHISTO                                                         4019
#define IDH_HISTO_MOVETOBARCHARTVIEW                                                     4020
#define IDH_HISTO_MOVETOHISTOVIEW                                                        4021
#define IDH_HISTO_PROPERTIES                                                             4022
#define IDH_HISTO_REPORT_COMBO                                                           4023
#define IDH_HISTO_RESOURCE_COMBO                                                         4024
#define IDH_HISTO_ROW_INDICATOR                                                          4025
#define IDH_OETB_CALENDAR                                                                4026
#define IDH_OETB_CODE_LINK_CATEGORY                                                      4027
#define IDH_OETB_DURATION_LINK_SLOPE                                                     4028
#define IDH_OETB_END_DATE                                                                4029
#define IDH_OETB_MOVE_END_DATE_LEFT                                                      4030
#define IDH_OETB_MOVE_END_DATE_RIGHT                                                     4031
#define IDH_OETB_MOVE_LEFT                                                               4032
#define IDH_OETB_MOVE_RIGHT                                                              4033
#define IDH_OETB_MOVE_START_DATE_LEFT                                                    4034
#define IDH_OETB_MOVE_START_DATE_RIGHT                                                   4035
#define IDH_OETB_PERCENTAGE_PROGRESS                                                     4036
#define IDH_OETB_START_DATE                                                              4037
#define IDH_PREVIEW_TOOLBAR_BORDER                                                       4038
#define IDH_PREVIEW_TOOLBAR_CLOSE_PREVIEW                                                4039
#define IDH_PREVIEW_TOOLBAR_EXPAND_TO_FIT_H                                              4040
#define IDH_PREVIEW_TOOLBAR_EXPAND_TO_FIT_V                                              4041
#define IDH_PREVIEW_TOOLBAR_LINES_PER_PAGE                                               4042
#define IDH_PREVIEW_TOOLBAR_LINES_PER_PAGE_VALUE                                         4043
#define IDH_PREVIEW_TOOLBAR_MOSAIC                                                       4044
#define IDH_PREVIEW_TOOLBAR_MULTI_PAGE                                                   4045
#define IDH_PREVIEW_TOOLBAR_ONE_PAGE                                                     4046
#define IDH_PREVIEW_TOOLBAR_PAGE_LAYOUT                                                  4047
#define IDH_PREVIEW_TOOLBAR_PAGINATE                                                     4048
#define IDH_PREVIEW_TOOLBAR_PRINT_CURRENT                                                4049
#define IDH_PREVIEW_TOOLBAR_PRINT_SETTINGS                                               4050
#define IDH_PREVIEW_TOOLBAR_TRUE_SIZE_H                                                  4051
#define IDH_PREVIEW_TOOLBAR_TRUE_SIZE_V                                                  4052
#define IDH_PREVIEW_TOOLBAR_TRY_TO_FIT_H                                                 4053
#define IDH_PREVIEW_TOOLBAR_TRY_TO_FIT_V                                                 4054
#define IDH_PREVIEW_TOOLBAR_USE_PAGE_BREAKS                                              4055
#define IDH_PREVIEW_TOOLBAR_WHATS_THIS                                                   4056
#define IDH_RES_MOD_TOOLBAR_ACTIVITY_FACTOR                                              4057
#define IDH_RES_MOD_TOOLBAR_ALLOCATION_QUANTITY                                          4058
#define IDH_RES_MOD_TOOLBAR_MODELLING_METHOD                                             4059
#define IDH_RES_MOD_TOOLBAR_RATE                                                         4060
#define IDH_RES_MOD_TOOLBAR_SELECT_RESOURCE                                              4061
#define IDH_RES_MOD_TOOLBAR_WORK_EFFORT                                                  4062
#define IDH_STANDARD_TOOLBAR_COPY                                                        4063
#define IDH_STANDARD_TOOLBAR_CURSOR_LOCATION                                             4064
#define IDH_STANDARD_TOOLBAR_CUT                                                         4065
#define IDH_STANDARD_TOOLBAR_DELETE                                                      4066
#define IDH_STANDARD_TOOLBAR_NEW_PROJECT                                                 4067
#define IDH_STANDARD_TOOLBAR_OPEN_LIBRARY_EXPLORER                                       4068
#define IDH_STANDARD_TOOLBAR_OPEN_PROJECT                                                4069
#define IDH_STANDARD_TOOLBAR_PASTE                                                       4070
#define IDH_STANDARD_TOOLBAR_PRINT                                                       4071
#define IDH_STANDARD_TOOLBAR_PRINT_PREVIEW                                               4072
#define IDH_STANDARD_TOOLBAR_PROPERTIES                                                  4073
#define IDH_STANDARD_TOOLBAR_REDO                                                        4074
#define IDH_STANDARD_TOOLBAR_SAVE_PROJECT                                                4075
#define IDH_STANDARD_TOOLBAR_SPELL_CHECK                                                 4076
#define IDH_STANDARD_TOOLBAR_TEXT_ANNOTATION                                             4077
#define IDH_STANDARD_TOOLBAR_UNDO                                                        4078
#define IDH_STANDARD_TOOLBAR_WHATS_THIS                                                  4079
#define IDH_STANDARD_TOOLBAR_ZOOM                                                        4080
#define IDH_BARCHART_TOOLBAR_RESCHEDULE_FWD_PASS_ONLY                                    4081
#define IDH_BARCHART_TOOLBAR_VIEW_PROJECT_TREE                                           4082
#define IDH_STANDARD_TOOLBAR_LICENCE_WIZARD												 4083
#define IDH_HISTO_HTILE                                                                  4084
#define IDH_STANDARD_TOOLBAR_P3_EXPORT												     4085
#define IDH_STANDARD_TOOLBAR_P3_IMPORT												     4086
#define IDH_BARCHART_TOOLBAR_CENTER_VIEW_ON_TASK                                         4087
#define IDH_BARCHART_TOOLBAR_HIDE_MARKED_ITEMS                                           4088
#define IDH_WIZARDS                                                                      4089
#define IDH_SELECT_WIZARDS                                                               4090
#define IDH_BARCHART_TOOLBAR_WBS_MANAGEMENT_DIALOG                                       4091
#define IDH_BARCHART_TOOLBAR_HIERARCHY_SHOW_SUBTASKS                                     4092
#define IDH_BARCHART_TOOLBAR_HIERARCHY_HIDE_SUBTASKS                                     4093
#define IDH_PREVIEW_TOOLBAR_SUMMARY_INFORMATION                                          4094
#define IDH_BARCHART_TOOLBAR_ROLL_UP_TO_ONE_LINE                                         4095
#define IDH_BARCHART_TOOLBAR_UNROLL_TASKS                                                4096
#define IDH_PREVIEW_TOOLBAR_DISPLAY_SWITCHES                                             4097
#define IDH_PREVIEW_TOOLBAR_PORTRAIT_ORIENTATION                                         4098
#define IDH_PREVIEW_TOOLBAR_LANDSCAPE_ORIENTATION                                        4099

// [Help ID Fixer report: Max ID = 4999]